"""Independent, hand-authored snapshot fixtures; no production format imports."""

import base64
import gzip
import hashlib
import io
import json
import struct
import tarfile
from pathlib import Path


SOURCE_SHA = "1" * 40
SITE_URL = "https://v8std.ru/"
MODEL = "v8std-hash-embeddings-v1"
MEMBERS = (
    "metadata.json", "pages.jsonl", "search-vectors.jsonl", "llms.txt", "llms-full.txt",
)
BODY = (
    "# Запросы\n\n[Стандарт](https://v8std.ru/std/437/?view=full#query)\n\n"
    '```bsl\nАдрес = "https://v8std.ru/std/437/";\n```'
)


def json_bytes(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True,
                      separators=(",", ":"), allow_nan=False).encode("utf-8")


def jsonl_bytes(rows):
    return b"".join(json_bytes(row) + b"\n" for row in rows)


def sha256(payload):
    return hashlib.sha256(payload).hexdigest()


def page_fixture(*, portable=True, site_url=SITE_URL):
    page = {
        "id": "std437", "type": "standard", "title": "Запросы",
        "description": "Параметры", "aliases": ["#std437"],
        "url": site_url + "std/437/", "markdown_url": site_url + "std/437.md",
        "source_path": "std/437.md", "source_urls": ["https://its.1c.ru/db/v8std#437"],
        "related": [], "body_markdown": BODY,
    }
    if portable:
        page.update(site_path="std/437/", markdown_path="std/437.md")
    return page


def vector_fixtures():
    # A valid finite one-hot vector, intentionally not generated by the producer.
    vector = base64.b64encode(struct.pack("<256f", 1.0, *([0.0] * 255))).decode("ascii")
    return [
        {"id": "std437", "field": field, "chunk_index": 0,
         "text_sha256": sha256(text.encode("utf-8")), "model": MODEL,
         "dim": 256, "vector_base64": vector}
        for field, text in [("metadata", "std437 Запросы Параметры #std437"), ("body", BODY)]
    ]


def corpus_files(*, pages=None, vectors=None):
    return {
        "pages.jsonl": jsonl_bytes([page_fixture()] if pages is None else pages),
        "search-vectors.jsonl": jsonl_bytes(vector_fixtures() if vectors is None else vectors),
        "llms.txt": "# Стандарты\n\n[Запросы](https://v8std.ru/std/437/)\n".encode(),
        "llms-full.txt": (BODY + "\n").encode(),
    }


def with_metadata(files, *, site_url=SITE_URL, mutate=None):
    descriptor = {
        "schema_version": 1, "source_sha": SOURCE_SHA, "canonical_site_url": site_url,
        "vector_model": MODEL, "vector_dim": 256,
        "files": {
            name: {"sha256": sha256(payload), "bytes": len(payload),
                   **({"rows": sum(bool(line.strip()) for line in payload.split(b"\n"))}
                      if name.endswith(".jsonl") else {})}
            for name, payload in files.items()
        },
    }
    if mutate:
        mutate(descriptor)
    metadata = {**descriptor, "corpus_id": sha256(json_bytes(descriptor))}
    return {"metadata.json": json_bytes(metadata), **files}


def tar_bytes(files, *, members=None, tar_format=tarfile.USTAR_FORMAT):
    """members may contain hand-crafted TarInfo entries, including hostile ones."""
    output = io.BytesIO()
    with tarfile.open(fileobj=output, mode="w", format=tar_format) as archive:
        for member in MEMBERS if members is None else members:
            if isinstance(member, str):
                info = tarfile.TarInfo(member)
                content = files[member]
                info.size = len(content)
                info.mode = 0o644
            else:
                info, content = member
            archive.addfile(info, io.BytesIO(content))
    return output.getvalue()


def gzip_bytes(payload, *, filename="", mtime=0):
    output = io.BytesIO()
    with gzip.GzipFile(fileobj=output, mode="wb", filename=filename, mtime=mtime,
                       compresslevel=9) as archive:
        archive.write(payload)
    return output.getvalue()


def manifest_for(archive, files):
    metadata = json.loads(files["metadata.json"])
    digest = sha256(archive)
    return {
        "schema_version": 1, "source_sha": metadata["source_sha"],
        "corpus_id": metadata["corpus_id"], "vector_model": MODEL, "vector_dim": 256,
        "archive": {"path": digest + "/snapshot.tar.gz", "sha256": digest,
                    "bytes": len(archive), "unpacked_bytes": sum(map(len, files.values()))},
    }


def snapshot_fixture(*, files=None, members=None, tar_format=tarfile.USTAR_FORMAT):
    files = with_metadata(corpus_files()) if files is None else files
    archive = gzip_bytes(tar_bytes(files, members=members, tar_format=tar_format))
    return archive, manifest_for(archive, files)


def write_docs(root: Path, *, site_url=SITE_URL):
    files = corpus_files(pages=[page_fixture(portable=False, site_url=site_url)])
    for name, payload in files.items():
        path = root / ("ai" if name.endswith(".jsonl") else "") / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
    return files
