services:
  zensical:
    container_name: zensical
    build:
      context: ..
      dockerfile: docker-compose/docker/Dockerfile
    restart: "no"
    volumes:
      - ../:/docs
    working_dir: /docs
    command: build

  nginx:
    image: nginx:alpine
    restart: always    
    ports:
      - "8000:8080"
    volumes: 
      - ../site/:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
